spring.application.name=sivou-api

# H2 Database
spring.datasource.url=jdbc:h2:mem:sivoudb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Inicialización de SQL (Ejecuta schema.sql y data.sql)
spring.sql.init.mode=always

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
# CAMBIO IMPORTANTE: Usamos 'none' o 'validate' porque tú ya estás creando
# las tablas manualmente en schema.sql. Si dejas 'update', Hibernate
# intentará crearlas de nuevo y podrías tener errores de duplicidad.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# App
server.servlet.context-path=/api/v1